const useShoppingCartTypes = () => {
  const UPDATE_SHOPPING_CART = 'SHOPPING_CART::UPDATE_SHOPPING_CART';
  const ADD_PRODUCT = 'SHOPPING_CART::ADD_PRODUCT';
  const DELETE_SHOPPING_CART = 'SHOPPING_CART::DELETE_SHOPPING_CART';

  return { UPDATE_SHOPPING_CART, ADD_PRODUCT, DELETE_SHOPPING_CART };
};

export default useShoppingCartTypes;
